version: "3.8"

volumes:
  


services:

  nginx: 
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - 443:80
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php



