# FROM, RUN, COPY, CMD
ARG version=bullseye

FROM debian:${version}

RUN apt update && apt upgrade && apt install -y nginx

CMD ["nginx", "-g", "deamon off;"]

RUN apt update && apt ugpgrade && apt install -y php-fpm

CMD ["php-fpm8.2", "-F"]

